workspace:
  path: /go/src/github.com/ClaimCompass/sonar-runner-plugin

pipeline:
  test:
    image: golang:1.6
    environment:
      - CGO_ENABLED=0
    commands:
      - go vet
      - go test -cover -coverprofile=coverage.out
      - go build -ldflags "-s -w -X main.build=$DRONE_BUILD_NUMBER" -a -tags netgo

  build:
    image: plugins/docker
    repo: claimcompass/sonar-runner
    secrets: [ docker_username, docker_password ]
    auto_tag: true
    when:
      event: [ tag, push ]
      branch: [ master, hotfix/* ]
